include theos/makefiles/common.mk

BUNDLE_NAME = MShuffleSettings
MShuffleSettings_FILES = /mnt/d/codes/mshuffle/mshufflesettings/MShuffleSettingsController.mm
MShuffleSettings_INSTALL_PATH = /Library/PreferenceBundles
MShuffleSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
MShuffleSettings_PRIVATE_FRAMEWORKS = Preferences
MShuffleSettings_CFLAGS = -fobjc-arc
MShuffleSettings_LDFLAGS = -Wl,-segalign,4000
MShuffleSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk
